pluginManagement {
    repositories {
        gradlePluginPortal()
        google()
    }
}

dependencyResolutionManagement {
    repositoriesMode.set(RepositoriesMode.FAIL_ON_PROJECT_REPOS)
    repositories {
        google()
        mavenCentral()
        maven { url "https://jitpack.io" }
    }
}

rootProject.name='PojavLauncher'
include ':app_pojavlauncher'
include ':forge_installer'
include ':glfw:jni_bindings'
include ':mojoexec:jni_bindings'
include ':sdl:jni_bindings'

// Map each included Android library project directly to the Gradle module
// inside its checked-out Git submodule.
project(':glfw:jni_bindings').projectDir = file('app_pojavlauncher/src/main/jni/glfw/jni_bindings')
project(':mojoexec:jni_bindings').projectDir = file('app_pojavlauncher/src/main/jni/mojoexec/jni_bindings')
project(':sdl:jni_bindings').projectDir = file('app_pojavlauncher/src/main/jni/sdl/jni_bindings')
